name: Pipeline DevSecOps

# Pipeline akan berjalan otomatis setiap ada kode baru di branch main atau master
on:
  push:
    branches: [ "main", "master" ]

jobs:
  sast_scan:
    name: Pemindaian SAST (Bandit)
    runs-on: ubuntu-latest
    steps:
      # 1. Mengambil kodemu dari repositori (Diupdate ke v4)
      - name: Mengambil Source Code
        uses: actions/checkout@v4

      # 2. Menyiapkan environment Python (Diupdate ke v5)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Memasang alat SAST Bandit
      - name: Install Bandit
        run: pip install bandit

      # 4. Menjalankan Bandit untuk mencari kerentanan keamanan
      - name: Menjalankan Scan SAST
        run: bandit -r . -f html -o bandit-report.html || true 

      # 5. Menyimpan hasil laporan (report) agar bisa kamu download (Diupdate ke v4)
      - name: Upload Laporan SAST
        uses: actions/upload-artifact@v4
        with:
          name: Laporan-SAST-Bandit
          path: bandit-report.html
